version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws sts get-caller-identity

  build:
    commands:
      - echo Deploying CloudFormation stack...
      - aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name create-iam-user \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              EnvName=dev \
              RoleName=sample-iam-role 

artifacts:
  files:
    - '**/*'