version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - echo "Installing AWS CLI v2..."
      - if ! command -v aws &> /dev/null; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
        else
          echo "AWS CLI v2 is already installed."
        fi
      - pip install --upgrade awscli


  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws sts get-caller-identity

  build:
    commands:
      - echo "verifying aws cli version..."
      - aws --version
      - which aws
      - echo "verfiying template.yaml..."
      - aws cloudformation validate-template --template-body file://template.yaml
      - echo Deploying CloudFormation stack...
      - aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name create-iam-user \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              EnvName=dev \
              RoleName=sample-iam-role 

artifacts:
  files:
    - '**/*'