version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11      

  pre_build:
    commands:
      - env
      - echo Logging in to AWS...
      - aws --version
      - aws sts get-caller-identity
      - pip install --quiet --upgrade pip
      - pip install --upgrade awscli
      - pip install --quiet --upgrade cfn-lint
      - cfn-lint --version

  build:
    commands:
      - |
        set -eux
        echo "Running Python syntax check"
        python -m py_compile $(find * -type f -name '*.py'
        echo "find template file"
        TEMPLATES="$(find ./cloudformation -type f)"
        echo "Found CloudFormation templates: $TEMPLATES"
        
        echo "verfiying template.yaml..."
        aws cloudformation validate-template --template-body file://template.yaml
        

artifacts:
  files:
    - '**/*'