AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild Service Role with CloudFormation and IAM permissions

Parameters:
  RoleName:
    Type: String
    Default: codebuild-service-role
    Description: Name of the CodeBuild service role
  
  ProjectName:
    Type: String
    Default: aws-project-build
    Description: Name of the CodeBuild project

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: Service role for CodeBuild with CloudFormation deployment permissions
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildCloudFormationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudFormation permissions
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackResource
                  - cloudformation:GetTemplate
                  - cloudformation:ListStacks
                  - cloudformation:ListStackResources
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ListChangeSets
                Resource: "*"
              
              # IAM permissions for creating roles and policies
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:UpdateRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:ListAttachedRolePolicies
                  - iam:ListRolePolicies
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:ListRoleTags
                Resource: "*"
              
              # S3 permissions for CloudFormation templates and artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                Resource: "*"
              
              # CodeBuild specific permissions
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*"
              
              # Additional permissions for STS (for role assumption verification)
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: "*"

  # CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: CodeBuild project for deploying CloudFormation templates
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: GITHUB
        Location: https://github.com/amolmane1939/aws-project.git
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        PrivilegedMode: false
      Source:
        Type: GITHUB
        Location: https://github.com/amolmane1939/aws-project.git
        BuildSpec: buildspec.yaml
      TimeoutInMinutes: 15
      Tags:
        - Key: Name
          Value: !Ref ProjectName
        - Key: Purpose
          Value: CloudFormation-Deployment

Outputs:
  CodeBuildServiceRoleArn:
    Description: ARN of the CodeBuild service role
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildServiceRoleArn"
  
  CodeBuildServiceRoleName:
    Description: Name of the CodeBuild service role
    Value: !Ref CodeBuildServiceRole
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildServiceRoleName"
  
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildProjectName"
  
  CodeBuildProjectArn:
    Description: ARN of the CodeBuild project
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildProjectArn"
